import COLORS from '../../config/colors';
import {Dimensions, StyleSheet, Platform} from 'react-native';
const {height, width} = Dimensions.get('screen');
const height_logo = height * 0.1;
import {moderateScale} from '../../config/Metrics';
const styles = StyleSheet.create({
  inputIOS: {
    fontSize: 16,
    paddingLeft: 0,
    color: 'black',
  },
  inputAndroid: {
    fontSize: 16,
    paddingLeft: 0,
    color: 'black',
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  logo: {
    height: height_logo,
    width: height_logo,
  },
  text: {
    color: COLORS.dark,
  },
  titleText: {
    color: COLORS.dark,
    fontSize: 16,
  },
  header: {
    flex: 0.4,
    justifyContent: 'center',
    alignItems: 'center',
  },

  input: {
    borderColor: COLORS.primary,
    borderRadius: 2,
  },

  button: {
    alignItems: 'flex-end',
    marginTop: 30,
  },
  signIn: {
    marginTop: 15,
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    flexDirection: 'row',
  },
  textSingIn: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.light,
    paddingLeft: 15,
  },
  button: {
    alignItems: 'center',
    marginTop: 50,
  },
  textInput: {
    flex: 1,
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: '#000',
  },
  errorMsg: {
    color: '#FF0000',
    fontSize: 14,
  },
  text_header: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 30,
  },
  text_footer: {
    color: '#05375a',
    fontSize: 18,
    paddingBottom: 10,
    marginTop: -30,
  },
  action: {
    flexDirection: 'row',
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
  },
  actionError: {
    flexDirection: 'row',
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FF0000',
    paddingBottom: 5,
  },
  scrollview: {
    marginHorizontal: 5,
  },
  view: {
    padding: 10,
  },
  card: {
    marginHorizontal: 10,
    marginVertical: 10,
    padding: 5.3,
    width: moderateScale(375),
    height: moderateScale(135),
    borderRadius: 10,
    backgroundColor: COLORS.white,
  },
  cardText: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 25,
    justifyContent: 'flex-start',
  },
  image: {
    width: moderateScale(100),
    height:moderateScale(110),
    resizeMode: 'contain',
    borderRadius: 10,
  },
  image2: {
    paddingTop: moderateScale(10),
    width: Dimensions.get('window').width / 3.5,
    height: Dimensions.get('window').height / 6.5,
    resizeMode: 'contain',
    borderRadius: 10,
  },
  fullImage: {
    width: Dimensions.get('window').width / 1.03,
    height: Dimensions.get('window').height / 3,
    resizeMode: 'contain',
    borderRadius: 10,
    marginVertical: moderateScale(5),
    paddingHorizontal: 5,
  },
  elevation: {
    shadowColor: '#52006A',
    elevation: 4,
  },

  headerBanner: {
    flex: 0.4,
    width: width,
    backgroundColor: COLORS.bgColor,
  },
  headerText: {
    flex: 2,
    color: COLORS.white,
    marginVertical: 20,
    paddingHorizontal: 10,
    fontSize: 20,
    fontWeight: 'bold',
  },
  row: {
 
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  description: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: moderateScale(10),
    paddingHorizontal: moderateScale(10),
  },
  description2: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: moderateScale(2),
    paddingHorizontal: moderateScale(10),
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    paddingLeft: 5,
    color: COLORS.dark,
  },
  descriptionText: {
    paddingHorizontal: 5,
    fontSize: 12,
    color: COLORS.dark,
  },
  strike: {
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  buynow: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.success,
    width: moderateScale(100),
    height: moderateScale(40),
    borderRadius: 8,
    shadowColor: COLORS.successDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  demo: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    width: moderateScale(100),
    height: moderateScale(40),
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  demo2: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#33B5FF',
    width: moderateScale(100),
    height: moderateScale(40),
    borderRadius: 8,
  },
  courseTile: {
    marginVertical: 5,
    justifyContent: 'space-evenly',
    alignContent: 'flex-start',
    color: COLORS.dark,
  },
  activityIndicator: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 80,
  },
  row2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(10),
    justifyContent: 'space-between',
  },
  row3: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: moderateScale(10),
    paddingTop: moderateScale(20),
    justifyContent: 'space-between',
  },
  line: {
    width: Dimensions.get('window').width / 1,
    height: 1,
    backgroundColor: 'black',
  },
  typeButton: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    padding: moderateScale(10),
  },
  activeButton: {
    height: moderateScale(37),
    backgroundColor: COLORS.primary,
    width: moderateScale(100),
    borderRadius: 20,
    marginHorizontal: moderateScale(5),
  },
  default: {
    height: moderateScale(37),
    backgroundColor: COLORS.dark,
    width: moderateScale(100),
    borderRadius: 20,
    marginHorizontal: moderateScale(5),
  },
  typeText: {
    textAlign: 'center',
    paddingVertical: moderateScale(6),
    color: COLORS.light,
    fontSize: 17,
  },
  viewVideos: {
    height: moderateScale(35),
    backgroundColor: COLORS.bgColor,
    width: moderateScale(100),
    borderRadius: 20,
    marginHorizontal: moderateScale(110),
  },
  folder: {
    flex: 1,
    maxWidth: moderateScale(100),
    height: moderateScale(110),
    backgroundColor: COLORS.light,
    paddingVertical: moderateScale(17),
    paddingHorizontal: moderateScale(10),
  
  },
  column: {
    flex: 1,
    paddingHorizontal: moderateScale(20),
    paddingVertical: moderateScale(10),
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
  layer: {
    backgroundColor: 'white',
    zIndex: 1,
    margin: 2,
    borderRadius: 10,
    borderWidth: 2,
  },
  oldPrice: {
    textDecorationLine: 'line-through',
    color: 'red',
    textDecorationStyle: 'solid',
    fontSize: 14,
    fontWeight: 'bold',
  },
  price: {
    textDecorationStyle: 'solid',
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.dark,
  },
  searchContainer: {
    margin: 15,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    width: '90%',
  },
  searchInput: {
    fontSize: 20,
    width: '100%',
    padding: 10,
    flexDirection: 'row',
    backgroundColor: '#d9dbda',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    color: 'black',
  },
  chatBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.red,
    width: moderateScale(150),
    height: moderateScale(40),
    borderRadius: 8,
    marginHorizontal: moderateScale(0),
  },
  description3: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    marginLeft: Dimensions.get('window').width / 2.9,
    marginTop: 5,
  },
  chatBtn2: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bgColor,
    width: moderateScale(200),
    height: moderateScale(40),
    borderRadius: 18,
    marginHorizontal: moderateScale(10),
  },
  footer: {
    flex: 3,
    backgroundColor: COLORS.white,
  },
});
export default styles;
